# Generated by Django 2.0.2 on 2019-03-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupDescriptionPreset',
            fields=[
                ('GrupCd', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('GrupTitle', models.TextField(default='預設行程標題', max_length=50, unique=True)),
                ('GrupContent', models.TextField(default='預設行程內容', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TourData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrupSnm', models.TextField(max_length=50)),
                ('GrupLn', models.TextField(max_length=50)),
                ('LeavDt', models.TextField(max_length=50)),
                ('AgtAm', models.TextField(max_length=50)),
                ('SaleYqt', models.TextField(max_length=50)),
                ('EstmYqt', models.TextField(max_length=50)),
                ('GrupDescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrawlerServer_app.GrupDescriptionPreset')),
            ],
        ),
    ]
